### ISSUE TITLE
Done callback not getting called.

### ISSUE THREAD

**Issue by mathurs** [goodeggs/mongoose-querystream-worker#6]
I implemented the callback version of this and while it used to work earlier, with the most recent version the final callback doesn't seem to be getting called. Have checked that I am calling done() for every row.

**Comment by hurrymaplelad** [comment]
Hi @mathurs, I can't reproduce the error you're describing. Can you provide any more details? [Here's a test](https://github.com/hurrymaplelad/mongoose-querystream-worker/blob/master/test/querystream.work.test.js#L57) that should verify that the final callback is called. The test passes locally for me and on TravisCI. If you can make it fail, I can definitely help.

**Comment by serhalp** [comment]
This module [has been deprecated](https://github.com/goodeggs/mongoose-querystream-worker/pull/9).
