### ISSUE TITLE
DeprecationWarning Mongoose

### ISSUE THREAD

**Issue by jacinto123** [goodeggs/mongoose-querystream-worker#7]
Package.json
"dependencies": {
    "mongoose": "^4.6.0",
    "mongoose-querystream-worker": "^3.0.1"
  },

The use:
Model.customer.find({'id' : 40721}).stream().concurrency(5).work(onCustomerEach);

Returns:
(node:2340) DeprecationWarning: Mongoose: Query.prototype.stream() is deprecated in mongoose >= 4.5.0, use Query.prototype.cursor() instead.

If I use cursor then concurrency is not found. Thanks Again!

**Comment by serhalp** [comment]
This module [has been deprecated](https://github.com/goodeggs/mongoose-querystream-worker/pull/9).
